name: Build DLL on Changes

on:
  push:
    branches: [ "main" ]
    paths:
      - 'BeautyFolder.cs'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x' # 或者你所需的特定版本

    - name: Build and publish DLL
      run: |
        dotnet build --configuration Release
        dotnet publish --configuration Release --output ./publish
      working-directory: ./ # 确保这是您项目文件的路径

    - name: Upload DLL Artifact
      uses: actions/upload-artifact@v3
      with:
        name: BeautyFolder.dll
        path: ./publish/BeautyFolder.dll # 确保这是您发布输出的正确路径
